advcbv/advcbv/urls.py
from django.urls import path,include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app'))
]

advcbv/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
#   path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    School = models.ForeignKey(School,on_delete=models.CASCADE,related_name='students')

    def __str__(self):
        return self.name

advcbv/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import (View,TemplateView,
                                  ListView,DetailView,
                                  CreateView,UpdateView,
                                  DeleteView)
from . import models

def index(request):
     return render(request,'index.html')

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ("name","principal","location")
    model = models.School
   
class SchoolUpdateView(UpdateView):
    fields = ("name","principal","location")
    model = models.School

class CBView(View):
    def get(self,request):
        return HttpResponse('Class Base Views are Cools')

advcbv/basic_app/templates/basic_app/basic_app_base.html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
        <title>Base</title>
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:create' %}">Create</a></li>
                <li><a href="#"></a></li>
            </ul>

        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
        
        
    </body>
    </html>

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School details:</h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students:</h3>

    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} year old.</p>
    {% endfor %}

</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>

</div>


{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="sumbit" class="btn btn-primary" value="Sumbit">

</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}

<h1>Welcome to a list of all the schools!</h1>
<ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href="#"></a></li>
        </ul>

    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    
    
</body>
</html>

advcbv/templates/index.html
{% extends "base.html" %}
    {% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
        
    </div>
    {% endblock %}